version: '3'

services:
   db:
     container_name: mysql_db_1
     image: mysql:5.5
     volumes:
       - /home/alex/dev/docker/mysql/db_data:/var/lib/mysql
       - /home/alex/dev/docker/mysql/share:/recreateDb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: pwdroot
volumes:
    db_data:
    share:
